#!/bin/sh


# statusbar loop

while true; do
    xsetroot -name "$(date "+%a %d %m %Y") $(cat /sys/class/power_supply/BAT0/capacity)%"
    sleep 1m
done &

# Autostart section
remaps &
nitrogen --restore &

dwm 2 > $HOME/.local/share/dwm-log

