#!/bin/sh
# This script selects a single monitor to be displayed using mons

pmon=$(mons | grep ^[0-9] | awk '{print $2}' | dmenu -i -l 5 -p "Select the ONLY monitor to be displayed")

mons --primary $pmon
mons -o
